### PR TITLE
Overhaul for version 1.0.0. See CHANGELOG.md.

### PR DESCRIPTION
**Pull request by brannondorsey**
Hi there, this tool is super great! I've spent the weekend working with it and I've added lots of features. You can see a description of all of the changes I've made in the CHANGELOG.md, but they mainly include:

- Add command-line arguments
- Optionally save pastes as `.txt` files
- Optionally download trending pastes once an hour
- Improved logging
- Bug fixes

If you like where this is headed, would you consider merging?

I've overhauled a lot of the code, which is the reason for the version bump to `v1.0.0`. Thats mainly to notify peoples of breaking changes (mainly through the CLI args). `1.0.0` was really a judgment call, if you would like it could totally be something else.

Thanks for your hard work on making this tool!

### CODE REVIEW

**Comment by imnotjames** [comment]
Hey Brannon,  this is awesome.  I'm going to try to look it over this weekend to get it merged in.  Thank you so much!

**Comment by brannondorsey** [comment]
Sure thing! Let me know if you have any questions about the code or if you
find any issues. I've been running it for around half a week and its
working well.

One thing I did notice is that making LIKE queries on the paste_contents
column don't seem to work for me. Meaning that pastebin.db isn't searchable
:/ Haven't had too much time to look in to that, but any thoughts?

Cheers!

PGP Public Key <https://keybase.io/brannondorsey/pgp_keys.asc>
http://brannondorsey.com
@brannondorsey <https://twitter.com/brannondorsey>

**Comment by imnotjames** [comment]
What is the query?  I didn't had those issues.

**Comment by brannondorsey** [comment]
Any query like:

```
SELECT * FROM paste_content WHERE raw_content LIKE "%example%"
```

returns 0 results for all LIKE values, even when I'm positive the search string is in at least one raw_content column. Queries on the paste_key column however do work:

```
SELECT * FROM paste_content WHERE paste_key LIKE "%pFWsM98L%"
```

**Comment by brannondorsey** [comment]
Would you mind confirming checking if this is also the case for you?

**Comment by imnotjames** [comment]
@brannondorsey 
It seems to work here:

```
SELECT paste_key FROM paste_content WHERE raw_content LIKE '%Charmander%' LIMIT 1;
```

Returns the paste `9gQ8mX9y`: http://pastebin.com/raw/9gQ8mX9y

For your example:

```
SELECT paste_key FROM paste_content WHERE raw_content LIKE "%example%" LIMIT 1;
```

Returns the paste `4HRBah6F`: http://pastebin.com/raw/4HRBah6F



What version of SQLite are you using (`sqlite --version`)?  What's the schema of `paste_content` (`.schema paste_content`)?  What's your encoding (`PRAGMA encoding;`)?

For reference:

Version:  `3.18.0 2017-03-28 18:48:43 424a0d380332858ee55bdebc4af3789f74e70a2b3ba1cf29d84b9b4bcf3e2e37`

Schema: `CREATE TABLE paste_content (paste_key CHAR(8) PRIMARY KEY, raw_content TEXT);`

Encoding: `UTF-8`

**Comment by brannondorsey** [comment]
Very strange, I just ran your example queries and still 0 results. Again, I confirmed that "example" string was in the database.

Version: `3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f`
PRAGMA encoding: `UTF-8`
Schema: 
```
CREATE TABLE paste (
                paste_key CHAR(8) PRIMARY KEY,
                timestamp TIMESTAMP,
                size INT,
                expires TIMESTAMP,
                title TEXT,
                syntax TEXT,
                user TEXT NULL
            );
CREATE TABLE paste_content (
                paste_key CHAR(8) PRIMARY KEY,
                raw_content TEXT
            );
```

I will try upgrading my `sqlite3` version to match yours and report back.

**Comment by brannondorsey** [comment]
Here is a zip of the small database I am using for testing. Can you confirm your queries work on this DB?

[pastebin.db.zip](https://github.com/imnotjames/pastebin-mirror/files/1154633/pastebin.db.zip)

**Comment by imnotjames** [comment]
For testing I downgraded to the earliest version of `sqlite3` I have in my package cache: `3.13.0 2016-05-18 10:57:30 fc49f556e48970561d7ab6a2f24fdd7d9eb81ff2`

I could not replicate the issue with that version.

Given the database you uploaded, I was able to run:

```
SELECT paste_key FROM paste_content WHERE raw_content LIKE '%example%' LIMIT 1;
```

And I received the following paste: `fbtUty4Z`

```
### this is example

    int main(void) {
        printf("hello world\n");
        return 0;
    }
```

**Comment by imnotjames** [comment]
Also, in case it matters, I'm using a 64bit operating system.

**Comment by brannondorsey** [comment]
Very strange indeed. I am using a 64-bit Ubuntu OS. Having trouble finding a quick `sqlite3` upgrade (`sudo apt install --upgrade sqlite3` after an `apt update` doesn't suffice) but I will keep looking. I'm not a heavy SQL user, I wonder if I am doing something silly...

**Comment by imnotjames** [comment]
I am also able to find the row using http://inloop.github.io/sqlite-viewer/ , loading the file, and using the query `SELECT paste_key FROM paste_content WHERE raw_content LIKE '%example%' LIMIT 1;`

**Comment by brannondorsey** [comment]
The odd thing is that queries on the `paste_key` column work fine:

```
sqlite> SELECT paste_key FROM paste_content WHERE paste_key LIKE '%5%' LIMIT 1;
2b7jJ6S5
```

**Comment by brannondorsey** [comment]
Weeeeird... I am able to confirm that uploading to http://inloop.github.io/sqlite-viewer and executing the query works. Searching for an `sqlite3` update.

**Comment by brannondorsey** [comment]
Just upgraded to version:
```
3.19.3 2017-06-08 14:26:16 0ee482a1e0eae22e08edc8978c9733a96603d4509645f348ebf55b579e89636b
```
And still 0 results. As a sanity check, I'm running:

```
$ sqlite3 pastebin.db
sqlite> SELECT paste_key FROM paste_content WHERE raw_content LIKE '%example%' LIMIT 1;
```
Is there anything obvious that I might be missing? I'm also running _DB Browser for SQLite_ and those queries also don't work.

**Comment by brannondorsey** [comment]
I just tried the same commands on a virtual machine with a fresh install of Kali linux and I'm still having the issue. Which makes me feel like its a me-problem of some sort. Sorry to bug, but is the above process:
```
$ sqlite3 pastebin.db
sqlite> SELECT paste_key FROM paste_content WHERE raw_content LIKE '%example%' LIMIT 1;
```

How I should be executing these queries?

**Comment by imnotjames** [comment]
@brannondorsey I've found the issue.

The same issue is happening here in Kali linux live environment in Virtualbox, so you aren't crazy.

## What happened?

The issue is that the compile option `LIKE_DOESNT_MATCH_BLOBS` is used in the various builds of SQlite in Kali, Ubuntu, etc.  (Why?  I don't know.)

One way we can correct this could be to try to include the pastes as a text type rather than a binary - but pastebin data could have non-text information included.. things outside UTF-8.  It might take some experimentation to get something that doesn't lose data but also isn't affected by this..

One way to work around this for now is to use:

```
SELECT paste_key FROM paste_content WHERE CAST(raw_content AS TEXT) LIKE '%example%' LIMIT 1;
```


## How did I figure this out?

In grabbed Kali and set up a VM and downloaded the database file.

The query works when doing:
```
SELECT paste_key FROM paste_content WHERE CAST(raw_content AS TEXT) LIKE '%example%' LIMIT 1;
```

And this matches nothing, when it should match anything:
```
SELECT paste_key FROM paste_content WHERE raw_content LIKE '%' LIMIT 1;
```

Also, when manually resetting the field by updating it to itself it corrects the issues: 
```
UPDATE paste_content SET raw_content = CAST(raw_content AS TEXT) LIMIT 1;
```


Checking the different fields with:
```
SELECT TYPEOF(raw_content) FROM paste_content WHERE raw_content NOT LIKE '%' LIMIT 1;
SELECT TYPEOF(raw_content) FROM paste_content WHERE raw_content LIKE '%' LIMIT 1;
```

The ones that work are marked as `text`, and the ones that don't are marked as `blob`.

This made me start to dig into weirdness that could affect `LIKE` and blobs, which led me to: https://sqlite.org/compile.html

Lo and behold, `PRAGMA compile_options` on Kali linux shows it *does* have that set, and when I check locally it's not there.

**Comment by brannondorsey** [comment]
```
SELECT paste_key FROM paste_content WHERE CAST(raw_content AS TEXT) LIKE '%example%' LIMIT 1;
```

Worked like a charm! +1 and huge thanks for installing a VM just to dig into this solution, it is really appreciated :+1: I figure its probably best to keep storing pastes as blobs so as to not degrade the content of the archive. And then perhaps we could mention the cast solution in the README. What do you think?

What are your thoughts on the changes I've proposed btw (no worries if you haven't gotten around to reviewing them yet)?

**Comment by imnotjames** [comment]
Hey @brannondorsey 

I do have to say, thank you _so_ much for the amount of work you put in.

I have looked at this code a bit, and I don't think I'll merge it in as-is.  It does point out a few bugs.  I have updated master to fix those bugs.

Splitting trending pastes and not into different tables is a bit weird to me. Trending pastes have users associated, and regular pastes have hits.  I'm not sure what separating them will help with.

Regarding File Output: I am always iffy about flat file output.  This is because with most linux distributions, those using ext will have a lot of trouble when storing many files, numbering in the tens of millions.  My laptop can only store `27,025,408` files.  So eventually I'd end up running out of inodes.  There's also performance hits on ext when you go over 100k files in a directory.  With NTFS you'll have fewer issues, but you will run into performance issues.  

I also don't see the benefit of file output over SQLite.

**Comment by brannondorsey** [comment]
Hey @imnotjames, no problem. Your code was a pleasure to read and launched me leaps and bounds forward towards some of my personal pastebin archiving goals. So cheers to that!

As far as your concerns, I totally understand if you don't feel like these changes are appropriate to move into your `master`. Let me explain a few of my motivations for design choices. I separated trending posts into their own table because I wanted to add support to use this tool to archive pastebin trending even if the user didn't have a Pastebin PRO account and access to the Scraping API. Much of the work that I've been working on is analyzing credential leaks on Pastebin, which often "bubble" to the top of trending. For this analysis it is helpful for me know exactly what pastes are trending and when, without having to save all pastes. 

As for the flat file updates, that was a decision to make the archiver a bit more general purpose. While your argument against flatfile makes perfect sense for large archives (the performance hit is awful in comparison to SQLite), there are some instances where I was wanting to interface with flatfile directly without using SQLite. I also wanted to give users an option to access the files without being familiar with SQL.

Ive noticed a few more [issues](https://github.com/brannondorsey/pastebin-mirror/issues) (likely with my implementation) that I intend to fix in the next week or so. But if you prefer not to include my changes, how would you feel about a hard fork? I have interest in distributing some version of this via pip for easy download. Once a few more of the bugs are ironed out.

**Comment by imnotjames** [comment]
> As far as your concerns, I totally understand if you don't feel like these changes are appropriate to move into your master. Let me explain a few of my motivations for design choices. I separated trending posts into their own table because I wanted to add support to use this tool to archive pastebin trending even if the user didn't have a Pastebin PRO account and access to the Scraping API. Much of the work that I've been working on is analyzing credential leaks on Pastebin, which often "bubble" to the top of trending. For this analysis it is helpful for me know exactly what pastes are trending and when, without having to save all pastes.

Why not have a separate table to record a paste key and a time when it was found in "trending"?  That way there's a clearer distinction, you record when you saw it (and can duplicate that trending find?) but also remove the need for branching code paths.

Also, I have a patch I'm going to be getting in shortly to get around the problem of the requirement for a pastebin pro account.

> Ive noticed a few more issues (likely with my implementation) that I intend to fix in the next week or so. But if you prefer not to include my changes, how would you feel about a hard fork? I have interest in distributing some version of this via pip for easy download. Once a few more of the bugs are ironed out.

You're free to hard fork as you'd like (:

**Pull request closed without merging**
